# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/degaswifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/degaswifi/proprietary/bin/atcmdsrv:system/bin/atcmdsrv \
    vendor/samsung/degaswifi/proprietary/bin/cploader:system/bin/cploader \
    vendor/samsung/degaswifi/proprietary/bin/hwacc:system/bin/hwacc \
    vendor/samsung/degaswifi/proprietary/bin/serial_cfun0:system/bin/serial_cfun0 \
    vendor/samsung/degaswifi/proprietary/bin/serial_client:system/bin/serial_client \
    vendor/samsung/degaswifi/proprietary/bin/diag:system/bin/diag \
    vendor/samsung/degaswifi/proprietary/bin/eeh:system/bin/eeh \
    vendor/samsung/degaswifi/proprietary/bin/nvm:system/bin/nvm \
    vendor/samsung/degaswifi/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/degaswifi/proprietary/bin/simal:system/bin/simal \
    vendor/samsung/degaswifi/proprietary/bin/telmon:system/bin/telmon \
    vendor/samsung/degaswifi/proprietary/bin/vcm:system/bin/vcm \
    vendor/samsung/degaswifi/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/samsung/degaswifi/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/degaswifi/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/degaswifi/proprietary/lib/libsimal.so:system/lib/libsimal.so \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_gain_calibration.xml:system/etc/tel/ttc/audio_gain_calibration.xml \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_avc.nvm:system/etc/tel/ttc/audio_avc.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_config.nvm:system/etc/tel/ttc/audio_config.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_ctm.nvm:system/etc/tel/ttc/audio_ctm.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_diamond.nvm:system/etc/tel/ttc/audio_diamond.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_DualMic.nvm:system/etc/tel/ttc/audio_DualMic.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_ec.nvm:system/etc/tel/ttc/audio_ec.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_eq.nvm:system/etc/tel/ttc/audio_eq.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_gain_calibration.xml:system/etc/tel/ttc/audio_gain_calibration.xml \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_gssp_config.nvm:system/etc/tel/ttc/audio_gssp_config.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_HLPF.nvm:system/etc/tel/ttc/audio_HLPF.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_misc.nvm:system/etc/tel/ttc/audio_misc.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_MSAmain.nvm:system/etc/tel/ttc/audio_MSAmain.nvm \
    vendor/samsung/degaswifi/proprietary/etc/tel/ttc/audio_ns.nvm:system/etc/tel/ttc/audio_ns.nvm \
    vendor/samsung/degaswifi/proprietary/bin/backup_log.sh:system/bin/backup_log.sh \
    vendor/samsung/degaswifi/proprietary/bin/close_aud_path_fm.sh:system/bin/close_aud_path_fm.sh \
    vendor/samsung/degaswifi/proprietary/bin/close_aud_path_hifi_headset.sh:system/bin/close_aud_path_hifi_headset.sh \
    vendor/samsung/degaswifi/proprietary/bin/dvfm_control.sh:system/bin/dvfm_control.sh \
    vendor/samsung/degaswifi/proprietary/bin/exit_composite.sh:system/bin/exit_composite.sh \
    vendor/samsung/degaswifi/proprietary/bin/hw.sh:system/bin/hw.sh \
    vendor/samsung/degaswifi/proprietary/bin/open_aud_path_fm_headset.sh:system/bin/open_aud_path_fm_headset.sh \
    vendor/samsung/degaswifi/proprietary/bin/open_aud_path_fm_speaker.sh:system/bin/open_aud_path_fm_speaker.sh \
    vendor/samsung/degaswifi/proprietary/bin/open_aud_path_hifi_headset.sh:system/bin/open_aud_path_hifi_headset.sh \
    vendor/samsung/degaswifi/proprietary/bin/run_composite.sh:system/bin/run_composite.sh \
    vendor/samsung/degaswifi/proprietary/etc/gfx.cfg:system/etc/gfx.cfg \
    vendor/samsung/degaswifi/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/degaswifi/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/degaswifi/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/degaswifi/proprietary/lib/libGLESv2SC.so:system/lib/libGLESv2SC.so \
    vendor/samsung/degaswifi/proprietary/lib/libceu.so:system/lib/libceu.so \
    vendor/samsung/degaswifi/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/degaswifi/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/degaswifi/proprietary/lib/libgputex.so:system/lib/libgputex.so \
    vendor/samsung/degaswifi/proprietary/lib/libmvmem.so:system/lib/libmvmem.so \
    vendor/samsung/degaswifi/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/libacm.so:system/lib/libacm.so \
    vendor/samsung/degaswifi/proprietary/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/degaswifi/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/degaswifi/proprietary/lib/libippimgp.so:system/lib/libippimgp.so \
    vendor/samsung/degaswifi/proprietary/lib/libippsp.so:system/lib/libippsp.so \
    vendor/samsung/degaswifi/proprietary/lib/libippvp.so:system/lib/libippvp.so \
    vendor/samsung/degaswifi/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/degaswifi/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v04004.so:system/lib/lib_Samsung_SB_AM_for_ICS_v04004.so \
    vendor/samsung/degaswifi/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/degaswifi/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/degaswifi/proprietary/lib/soundfx/libmrvlpreprocessing.so:system/lib/soundfx/libmrvlpreprocessing.so \
    vendor/samsung/degaswifi/proprietary/etc/audio_basic_element.xml:system/etc/audio_basic_element.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_coeff_config.xml:system/etc/audio_coeff_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/samsung/degaswifi/proprietary/etc/audio_gain_config.xml:system/etc/audio_gain_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_path_config.xml:system/etc/audio_path_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_swvol_calibration_def.xml:system/etc/audio_swvol_calibration_def.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_swvol_config.xml:system/etc/audio_swvol_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_swvol_element.xml:system/etc/audio_swvol_element.xml \
    vendor/samsung/degaswifi/proprietary/usr/lib/alsa-lib/libasound_module_ctl_codec.so:system/usr/lib/alsa-lib/libasound_module_ctl_codec.so \
    vendor/samsung/degaswifi/proprietary/usr/lib/alsa-lib/libasound_module_ctl_phone.so:system/usr/lib/alsa-lib/libasound_module_ctl_phone.so \
    vendor/samsung/degaswifi/proprietary/usr/lib/alsa-lib/libasound_module_pcm_phone.so:system/usr/lib/alsa-lib/libasound_module_pcm_phone.so \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/samsung/degaswifi/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/samsung/degaswifi/proprietary/etc/audio/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_BLUETOOTH_HEADSET.txt:system/etc/audio/Rx_ControlParams_BLUETOOTH_HEADSET.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_SECVOIP_BLUETOOTH_HEADSET.txt:system/etc/audio/Rx_ControlParams_SECVOIP_BLUETOOTH_HEADSET.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_SECVOIP_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SECVOIP_EARPIECE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_SECVOIP_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SECVOIP_SPEAKER_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_SECVOIP_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SECVOIP_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_SECVOIP_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SECVOIP_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_BLUETOOTH_HEADSET.txt:system/etc/audio/Tx_ControlParams_BLUETOOTH_HEADSET.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_SECVOIP_BLUETOOTH_HEADSET.txt:system/etc/audio/Tx_ControlParams_SECVOIP_BLUETOOTH_HEADSET.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_SECVOIP_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SECVOIP_EARPIECE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_SECVOIP_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SECVOIP_SPEAKER_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_SECVOIP_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SECVOIP_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_SECVOIP_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SECVOIP_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/LVVEFS_Rx_Configuration.txt:system/etc/audio_VR/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/LVVEFS_Tx_Configuration.txt:system/etc/audio_VR/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Rx_ControlParams_VR_BLUETOOTH_HEADSET.txt:system/etc/audio_VR/Rx_ControlParams_VR_BLUETOOTH_HEADSET.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Rx_ControlParams_VR_EARPIECE_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_EARPIECE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Rx_ControlParams_VR_SPEAKER_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_SPEAKER_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio_VR/Rx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Tx_ControlParams_VR_BLUETOOTH_HEADSET.txt:system/etc/audio_VR/Tx_ControlParams_VR_BLUETOOTH_HEADSET.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Tx_ControlParams_VR_EARPIECE_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_EARPIECE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Tx_ControlParams_VR_SPEAKER_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_SPEAKER_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio_VR/Tx_ControlParams_VR_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/degaswifi/proprietary/etc/camera_profiles.xml:system/etc/camera_profiles.xml \
    vendor/samsung/degaswifi/proprietary/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/degaswifi/proprietary/lib/libgpucsc.so:system/lib/libgpucsc.so \
    vendor/samsung/degaswifi/proprietary/lib/libionhelper.so:system/lib/libionhelper.so \
    vendor/samsung/degaswifi/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/degaswifi/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/degaswifi/proprietary/bin/FileMonitorService:system/bin/FileMonitorService \
    vendor/samsung/degaswifi/proprietary/etc/FileMonitorService.conf:system/etc/FileMonitorService.conf \
    vendor/samsung/degaswifi/proprietary/lib/libFileMonitorService.so:system/lib/libFileMonitorService.so \
    vendor/samsung/degaswifi/proprietary/bin/appCoda7542Dec:system/bin/appCoda7542Dec \
    vendor/samsung/degaswifi/proprietary/bin/appCoda7542Enc:system/bin/appCoda7542Enc \
    vendor/samsung/degaswifi/proprietary/lib/libcoda7542hal.so:system/lib/libcoda7542hal.so \
    vendor/samsung/degaswifi/proprietary/lib/libcoda7542.so:system/lib/libcoda7542.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecaacdec.so:system/lib/libcodecaacdec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecaacenc.so:system/lib/libcodecaacenc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecamrnbdec.so:system/lib/libcodecamrnbdec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecamrnbenc.so:system/lib/libcodecamrnbenc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecamrwbdec.so:system/lib/libcodecamrwbdec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecamrwbenc.so:system/lib/libcodecamrwbenc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodeccoda7542dec.so:system/lib/libcodeccoda7542dec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodeccoda7542enc.so:system/lib/libcodeccoda7542enc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodech263dec.so:system/lib/libcodech263dec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodech263enc.so:system/lib/libcodech263enc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodech264dec.so:system/lib/libcodech264dec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodech264enc.so:system/lib/libcodech264enc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecmp3dec.so:system/lib/libcodecmp3dec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecmpeg2dec.so:system/lib/libcodecmpeg2dec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecmpeg4dec.so:system/lib/libcodecmpeg4dec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecmpeg4enc.so:system/lib/libcodecmpeg4enc.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecpngdec.so:system/lib/libcodecpngdec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecwmadec.so:system/lib/libcodecwmadec.so \
    vendor/samsung/degaswifi/proprietary/lib/libcodecwmvdec.so:system/lib/libcodecwmvdec.so \
    vendor/samsung/degaswifi/proprietary/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/degaswifi/proprietary/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/degaswifi/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/degaswifi/proprietary/etc/mrvl_agps_default.conf:system/etc/mrvl_agps_default.conf \
    vendor/samsung/degaswifi/proprietary/etc/mrvl_gps_platform.conf:system/etc/mrvl_gps_platform.conf \
    vendor/samsung/degaswifi/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/degaswifi/proprietary/lib/libmtelif.so:system/lib/libmtelif.so \
    vendor/samsung/degaswifi/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/degaswifi/proprietary/etc/ams_list.xml:system/etc/ams_list.xml \
    vendor/samsung/degaswifi/proprietary/lib/libPowerSetting.so:system/lib/libPowerSetting.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/hwcomposer.mrvl.so:system/lib/hw/hwcomposer.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/lights.mrvl.so:system/lib/hw/lights.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/degaswifi/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/degaswifi/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/degaswifi/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/degaswifi/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so

#    vendor/samsung/degaswifi/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \

PRODUCT_COPY_FILES += \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/SDIO8887_SDIO_SDIO.bin:system/etc/firmware/mrvl/SDIO8887_SDIO_SDIO.bin \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/bt_cal_data.conf:system/etc/firmware/mrvl/bt_cal_data.conf \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/bt_init_cfg.conf:system/etc/firmware/mrvl/bt_init_cfg.conf \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/sd8887_uapsta.bin:system/etc/firmware/mrvl/sd8887_uapsta.bin \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/txpwrlimit_cfg.bin:system/etc/firmware/mrvl/txpwrlimit_cfg.bin
